// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxiManagerInfrastructure;

#nullable disable

namespace TaxiManagerInfrastructure.Data.Migrations
{
    [DbContext(typeof(TaxiManagerContext))]
    partial class TaxiManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxiManagerDomain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AutoPartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("dateTime");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("dateTime");

                    b.Property<Guid?>("MaintenanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlaceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("dateTime");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("AutoPartId")
                        .IsUnique()
                        .HasFilter("[AutoPartId] IS NOT NULL");

                    b.HasIndex("MaintenanceId")
                        .IsUnique()
                        .HasFilter("[MaintenanceId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("TaxiManagerDomain.Entities.AutoPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AutoPartName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MaintenanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaintenanceId");

                    b.ToTable("AutoPart", (string)null);
                });

            modelBuilder.Entity("TaxiManagerDomain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("dateTime");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("dateTime");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Enrollment", (string)null);
                });

            modelBuilder.Entity("TaxiManagerDomain.Entities.Maintenance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("EndDate")
                        .IsRequired()
                        .HasColumnType("dateTime");

                    b.Property<bool>("IsRepair")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("dateTime");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("VehicleMileage")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Maintenance", (string)null);
                });

            modelBuilder.Entity("TaxiManagerDomain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("TaxiManagerDomain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("dateTime");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("dateTime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<long>("NationalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Telephone")
                        .HasMaxLength(12)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("dateTime");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NationalId" }, "IX_User_NationalId")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("TaxiManagerDomain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("dateTime");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("dateTime");

                    b.Property<string>("Model")
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<string>("Nickname")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("dateTime");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<string>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Registration" }, "IX_Vehicle_Registration")
                        .IsUnique();

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("TaxiManagerDomain.Entities.Address", b =>
                {
                    b.HasOne("TaxiManagerDomain.Entities.AutoPart", "AutoPart")
                        .WithOne("WhereItWasPurchased")
                        .HasForeignKey("TaxiManagerDomain.Entities.Address", "AutoPartId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TaxiManagerDomain.Entities.Maintenance", "Maintenance")
                        .WithOne("WhereItWasMade")
                        .HasForeignKey("TaxiManagerDomain.Entities.Address", "MaintenanceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TaxiManagerDomain.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AutoPart");

                    b.Navigation("Maintenance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxiManagerDomain.Entities.AutoPart", b =>
                {
                    b.HasOne("TaxiManagerDomain.Entities.Maintenance", "Maintenance")
                        .WithMany("AutoParts")
                        .HasForeignKey("MaintenanceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("TaxiManagerDomain.Shared.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("AutoPartId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("varchar");

                            b1.HasKey("AutoPartId");

                            b1.ToTable("AutoPart");

                            b1.WithOwner()
                                .HasForeignKey("AutoPartId");
                        });

                    b.Navigation("Maintenance");

                    b.Navigation("Price");
                });

            modelBuilder.Entity("TaxiManagerDomain.Entities.Enrollment", b =>
                {
                    b.HasOne("TaxiManagerDomain.Entities.User", "Driver")
                        .WithMany("Enrollments")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Enrollment_Driver");

                    b.HasOne("TaxiManagerDomain.Entities.Vehicle", "Vehicle")
                        .WithMany("Enrollments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Enrollment_Vehicle");

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TaxiManagerDomain.Entities.Maintenance", b =>
                {
                    b.HasOne("TaxiManagerDomain.Entities.Vehicle", "Vehicle")
                        .WithMany("Maintenances")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("TaxiManagerDomain.Shared.Money", "LaborPrice", b1 =>
                        {
                            b1.Property<Guid>("MaintenanceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("varchar");

                            b1.HasKey("MaintenanceId");

                            b1.ToTable("Maintenance");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceId");
                        });

                    b.OwnsOne("TaxiManagerDomain.Shared.Money", "TotalPrice", b1 =>
                        {
                            b1.Property<Guid>("MaintenanceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("varchar");

                            b1.HasKey("MaintenanceId");

                            b1.ToTable("Maintenance");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceId");
                        });

                    b.Navigation("LaborPrice");

                    b.Navigation("TotalPrice");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("TaxiManagerDomain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_RoleId");

                    b.HasOne("TaxiManagerDomain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_UserId");
                });

            modelBuilder.Entity("TaxiManagerDomain.Entities.AutoPart", b =>
                {
                    b.Navigation("WhereItWasPurchased");
                });

            modelBuilder.Entity("TaxiManagerDomain.Entities.Maintenance", b =>
                {
                    b.Navigation("AutoParts");

                    b.Navigation("WhereItWasMade");
                });

            modelBuilder.Entity("TaxiManagerDomain.Entities.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("TaxiManagerDomain.Entities.Vehicle", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Maintenances");
                });
#pragma warning restore 612, 618
        }
    }
}
